#!/bin/bash
#PBS -P x69
#PBS -l walltime=48:00:00
#PBS -l ncpus=16
#PBS -l mem=16GB
#PBS -l jobfs=40GB
#PBS -l software=gaussian/g16c01
#PBS -l wd
#PBS -l storage=scratch/f81

module load gaussian/g16c01
cpulist=`grep Cpus_allowed_list: /proc/self/status | awk '{print $2}'`
echo %CPU=$cpulist > $PBS_JOBFS/filename.gjf
cat filename.gjf >> $PBS_JOBFS/filename.gjf
g16 < ${PBS_JOBNAME%.*}.gjf > ${PBS_JOBNAME%.*}.log 2>&1
